name: calendar_basic
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  intl: ^0.18.1
  lints: ^2.0.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  test: ^1.21.0
